### ISSUE TITLE
Missing entities after upgrade of this plugin

### ISSUE THREAD

**Issue by cosmos1978** [Hoffmann77/home_assistant_enphase_gateway#22] opened 2023-09-28 14:18 UTC
Since I updated through hacs to the latest version I am missing some important entities like current power production and lifetime production.

I tried reinstalling restarting etc. nothing is working

**Enphase installation**
Envoy-S Metered
door Enphase
Firmware: 7.6.175

**Home Assistant setup**
Software version: '2023.9.3'

**Screenshots**
![image](https://github.com/Hoffmann77/home_assistant_enphase_gateway/assets/20052785/eda672aa-f8fa-4b58-8233-b771c3f1ba12)

**Comment by cosmos1978** [comment] 2023-09-28 14:33
I downgraded from v1.2.1 to v1.0.1 and everything is working again.

So it seems something is broken in the latest version

**Comment by Hoffmann77** [comment] 2023-09-29 17:32
Hey @cosmos1978 ,
sorry for the inconvenience. Unfortunately I couldn't reproduce the issue on my own.
Could you reinstall version 1.2.1, enable debug logging and provide the necessary logs from Home Assistant?
If you need any help in the process please let me know.

**Comment by 26miller** [comment] 2023-10-01 12:44
I think I have the same issue as cosmos1978 I also lost the life production status. I think this happend to me when I installed v1.2.1 a couple of days ago. Just installed the v1.2.2 and same result. trying to figure out how to get back to v 1.0.1 to see it this fix it like cosmos1978 but not sure how to do that. Downloaded v.1.0.1 in HACS rebooted but it seems to me that I keep running v1.2.2

**Comment by Hoffmann77** [comment] 2023-10-01 17:23
Sorry to hear that,
If you want to upload logs so I can try to solve the issue you can:
1. settings -> Devices & services -> Enphase Gateway -> Enable debug logging 
2. restart Home Assistant
3. disable debug logging -> file will be downloaded automatically
4. upload the log file here.

Otherwise to roll back to version 1.0.1 it's best to:
1. remove the integration 
2. move to HACS and redownload version 1.0.1
3. restart Home Assistant 
4. go to settings -> Devices & services and add the integration

Hope I could help.

**Comment by 26miller** [comment] 2023-10-02 16:56
I created logfile and rolled back to v 1.0.1 after this the lifetime entity was working again.


[home-assistant_enphase_gateway_2023-10-02T16-37-14.760Z.log](https://github.com/Hoffmann77/home_assistant_enphase_gateway/files/12784729/home-assistant_enphase_gateway_2023-10-02T16-37-14.760Z.log)

**Comment by Hoffmann77** [comment] 2023-10-05 20:58
Hey,
thank you very much for the logfile.
Found the underlying issue and released a patch as beta release. You are welcome to give it a try.
I will perform some further tests and will release version 1.2.3 in the coming days.

**Comment by 26miller** [comment] 2023-10-06 16:31
Just installed the beta version and this seems to fix my problem. Thanks for the fast response!

I just found out entity is showing a value but is not increasing in value. I will create logfile again and roll back

**Comment by 26miller** [comment] 2023-10-07 11:13
I think I found the difference. The new version is counting in MWh and v1.0.1 is counting in Wh. Because of the rounding of the number, there is no activity shown every 15 minutes which makes it appear that it is not working

**Comment by Hoffmann77** [comment] 2023-10-08 13:20
Used the unit of measurement MWh for testing during development. Changed it back to Wh.

Next release will be back to Wh.

**Comment by Hoffmann77** [comment] 2023-10-14 14:00
Released version 1.2.3.
Closing this issue as resolved.

**Closed as completed by Hoffmann77** 2023-10-14 14:00 UTC
